openapi: '3.0.5'
info:
  title: Wichteln API
  version: 1.0.0
servers:
  - url: http://localhost:8080/wichteln/api
    description: Server description
paths:
  /users/${userId}/wichtelrunden:
    get:
      parameters:
        - $ref: '#/components/parameters/UserIdParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Wichtelrunde'
  /users/${userId}/wichtelrunden/${wichtelrundenId}:
    get:
      parameters:
        - $ref: '#/components/schemas/UserId'
        - $ref: '#/components/schemas/WichtelrundenId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wichtelrunde'
components:
  schemas:
    UserId:
      type: string
      pattern: '[A-Za-z0-9_-]+'
      minLength: 3
      maxLength: 12
      example: 'mohrm'
    WichtelrundenId:
      type: string
      pattern: '[A-Za-z0-9]+'
      minLength: 12
      maxLength: 12
      example: 'LKJwuqHaH71k'
    Wichtelrunde:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/WichtelrundenId'
        name:
          type: string
          example: 'Familienwichteln 2023'

  parameters:
    UserIdParam:
      name: userId
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/UserId'
    WichtelrundenIdParam:
      name: wichtelrundenId
      in: path
      required: true
      $ref: '#/components/schemas/WichtelrundenId'
      
